### PR TITLE
Feature/create mapping

### PR DESCRIPTION
**Pull request by blundski**
Up for discussion :)

No tests checked in yet so I am aware of that.

---
This change is [Reviewable](https://reviewable.io/reviews/exabel/python-sdk/17)

### CODE REVIEW

**Review by taral — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/exabel/python-sdk/17)* status: 0 of 1 files reviewed, 8 unresolved discussions (waiting on @blundski)

___
*[exabel_data_sdk/scripts/create_entity_mapping_from_csv.py, line 41 at r1](https://reviewable.io/reviews/exabel/python-sdk/17#-MSbzugUDEnCZ5ZNo-b2:-MSbzugUDEnCZ5ZNo-b3:bd60v9c) ([raw file](https://github.com/exabel/python-sdk/blob/8d66d9279ad667fc80a573e76f03d830b4a2a631/exabel_data_sdk/scripts/create_entity_mapping_from_csv.py#L41)):*
> ```Python
>         M;US;entityTypes/company/entities/company_C
> 
>     What to do if we can't find a mapping?
> ```

We could just leave those lines out, and maybe emit a warning.
___
*[exabel_data_sdk/scripts/create_entity_mapping_from_csv.py, line 69 at r1](https://reviewable.io/reviews/exabel/python-sdk/17#-MSc5VnK150jBK4iF4qQ:-MSc5VnK150jBK4iF4qR:b-q29cvm) ([raw file](https://github.com/exabel/python-sdk/blob/8d66d9279ad667fc80a573e76f03d830b4a2a631/exabel_data_sdk/scripts/create_entity_mapping_from_csv.py#L69)):*
> ```Python
>         )
>         self.parser.add_argument(
>             "--dry-run",
> ```

I’m not sure we need a dry-run argument when the only effect of the script is to produce a file. Although it does send a number of search requests, it makes no changes to the production environment, so the consequences of a faulty run aren’t as grave as for the scripts that create and delete resources.
___
*[exabel_data_sdk/scripts/create_entity_mapping_from_csv.py, line 81 at r1](https://reviewable.io/reviews/exabel/python-sdk/17#-MSc0Bb95BU5nyk0OCb2:-MSc0Bb95BU5nyk0OCb3:bqcbqrf) ([raw file](https://github.com/exabel/python-sdk/blob/8d66d9279ad667fc80a573e76f03d830b4a2a631/exabel_data_sdk/scripts/create_entity_mapping_from_csv.py#L81)):*
> ```Python
>         """
>         Entry method for creating mapping. Will sniff mapping_input to find id's to create
>         mappings for
> ```

According to the standard (https://www.python.org/dev/peps/pep-0257/) the first paragraph of a docstring should be a single sentence, which summarises the method. That sentence should describe the action the method performs, e.g. “Create a mapping from identifiers to tickers.” 

Then comes a blank line followed by a more elaborate explanation, if necessary.

(We don’t currently publish the documentation, but if and when we do, it’s convenient if our docstrings already follow the conventions.)
___
*[exabel_data_sdk/scripts/create_entity_mapping_from_csv.py, line 88 at r1](https://reviewable.io/reviews/exabel/python-sdk/17#-MSc1bCY61nPIPgdjhWf:-MSc1bCY61nPIPgdjhWg:bv1rqj9) ([raw file](https://github.com/exabel/python-sdk/blob/8d66d9279ad667fc80a573e76f03d830b4a2a631/exabel_data_sdk/scripts/create_entity_mapping_from_csv.py#L88)):*
> ```Python
>               mapping_input: the input ids to lookup mappings for
>         """
>         if hasattr(mapping_input, "ticker"):
> ```

Use `if "ticker" in mapping_input`.
___
*[exabel_data_sdk/scripts/create_entity_mapping_from_csv.py, line 92 at r1](https://reviewable.io/reviews/exabel/python-sdk/17#-MSc1kgO8PCtpVAamji_:-MSc1kgO8PCtpVAamjia:b-8lemsg) ([raw file](https://github.com/exabel/python-sdk/blob/8d66d9279ad667fc80a573e76f03d830b4a2a631/exabel_data_sdk/scripts/create_entity_mapping_from_csv.py#L92)):*
> ```Python
> 
>         print("No recognized id field in input file")
>         return mapping_input
> ```

In this case we don’t produce anything useful, in which case I don’t think it is helpful to just produce an output file identical to the input file. Rather, raise an exception, e.g. `raise ValueError("The input file has no field named 'ticker'.")`. The exception might be caught in `run_script` and the error message output to the user.
___
*[exabel_data_sdk/scripts/create_entity_mapping_from_csv.py, line 106 at r1](https://reviewable.io/reviews/exabel/python-sdk/17#-MSc2gCSBsqb1OyPmEgI:-MSc2gCSBsqb1OyPmEgJ:b-hqxuvc) ([raw file](https://github.com/exabel/python-sdk/blob/8d66d9279ad667fc80a573e76f03d830b4a2a631/exabel_data_sdk/scripts/create_entity_mapping_from_csv.py#L106)):*
> ```Python
>               mapping_input: the input ids to lookup mappings for
>         """
>         if hasattr(mapping_input, "ticker") and hasattr(mapping_input, "market"):
> ```

`if "ticker" in mapping_input and "market" in mapping_input`

But I think it would be a bit clearer to do the opposite, and raise an exception if the input does not satisfy the requirements:

```
if "ticker" not in mapping_input or "market" not in mapping_input:
    raise ValueError("The input file must have fields named 'ticker' and 'market'.")
```
___
*[exabel_data_sdk/scripts/create_entity_mapping_from_csv.py, line 126 at r1](https://reviewable.io/reviews/exabel/python-sdk/17#-MSc40Ak4_4mKiPndPb0:-MSc40Ak4_4mKiPndPb1:b-eszqon) ([raw file](https://github.com/exabel/python-sdk/blob/8d66d9279ad667fc80a573e76f03d830b4a2a631/exabel_data_sdk/scripts/create_entity_mapping_from_csv.py#L126)):*
> ```Python
>                     entity = client.entity_api.search_for_entities(
>                         entity_type=args.entity_type, mic=market, ticker=row["ticker"]
>                     )
> ```

This method returns a list of entities. For clarity, name this variable `entities`. We expect at most one entity to be returned, but I think we should verify that that is correct. If more than one entity is returned, we should emit a warning and not add any of them to the output.
___
*[exabel_data_sdk/scripts/create_entity_mapping_from_csv.py, line 144 at r1](https://reviewable.io/reviews/exabel/python-sdk/17#-MSc4hh27Od2B8gXWrTE:-MSc4hh27Od2B8gXWrTF:b-9ks7ev) ([raw file](https://github.com/exabel/python-sdk/blob/8d66d9279ad667fc80a573e76f03d830b4a2a631/exabel_data_sdk/scripts/create_entity_mapping_from_csv.py#L144)):*
> ```Python
>     def get_markets(self, market: str) -> List[str]:
>         """
>         Find the list of mic codes we will use to lookup for a given market
> ```

End the sentence with a period. Also, the ‘C’ in MIC stands for “code”, so just write “MICs” rather than “MIC codes”.

**Review by blundski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/exabel/python-sdk/17)* status: 0 of 4 files reviewed, 8 unresolved discussions (waiting on @taral)

___
*[exabel_data_sdk/scripts/create_entity_mapping_from_csv.py, line 41 at r1](https://reviewable.io/reviews/exabel/python-sdk/17#-MSbzugUDEnCZ5ZNo-b2:-MSc7rJ75eQokknZsZ9x:b-pbdqz3) ([raw file](https://github.com/exabel/python-sdk/blob/8d66d9279ad667fc80a573e76f03d830b4a2a631/exabel_data_sdk/scripts/create_entity_mapping_from_csv.py#L41)):*
<details><summary><i>Previously, taral wrote…</i></summary><blockquote>

We could just leave those lines out, and maybe emit a warning.
</blockquote></details>

Agreed.
___
*[exabel_data_sdk/scripts/create_entity_mapping_from_csv.py, line 69 at r1](https://reviewable.io/reviews/exabel/python-sdk/17#-MSc5VnK150jBK4iF4qQ:-MSc8nGiCmBVSObm2pze:bh7agqf) ([raw file](https://github.com/exabel/python-sdk/blob/8d66d9279ad667fc80a573e76f03d830b4a2a631/exabel_data_sdk/scripts/create_entity_mapping_from_csv.py#L69)):*
<details><summary><i>Previously, taral wrote…</i></summary><blockquote>

I’m not sure we need a dry-run argument when the only effect of the script is to produce a file. Although it does send a number of search requests, it makes no changes to the production environment, so the consequences of a faulty run aren’t as grave as for the scripts that create and delete resources.
</blockquote></details>

Agreed - removing
___
*[exabel_data_sdk/scripts/create_entity_mapping_from_csv.py, line 81 at r1](https://reviewable.io/reviews/exabel/python-sdk/17#-MSc0Bb95BU5nyk0OCb2:-MSc9TkD0MBnMtOuhCAD:b-ewmz2l) ([raw file](https://github.com/exabel/python-sdk/blob/8d66d9279ad667fc80a573e76f03d830b4a2a631/exabel_data_sdk/scripts/create_entity_mapping_from_csv.py#L81)):*
<details><summary><i>Previously, taral wrote…</i></summary><blockquote>

According to the standard (https://www.python.org/dev/peps/pep-0257/) the first paragraph of a docstring should be a single sentence, which summarises the method. That sentence should describe the action the method performs, e.g. “Create a mapping from identifiers to tickers.” 

Then comes a blank line followed by a more elaborate explanation, if necessary.

(We don’t currently publish the documentation, but if and when we do, it’s convenient if our docstrings already follow the conventions.)
</blockquote></details>

Fixed - also renamed method to get_entity_mapping / get_entity_mapping_by_ticker. I think this gives more information.
___
*[exabel_data_sdk/scripts/create_entity_mapping_from_csv.py, line 88 at r1](https://reviewable.io/reviews/exabel/python-sdk/17#-MSc1bCY61nPIPgdjhWf:-MScAFTc1PqBCvZGYGOG:b3mwcuc) ([raw file](https://github.com/exabel/python-sdk/blob/8d66d9279ad667fc80a573e76f03d830b4a2a631/exabel_data_sdk/scripts/create_entity_mapping_from_csv.py#L88)):*
<details><summary><i>Previously, taral wrote…</i></summary><blockquote>

Use `if "ticker" in mapping_input`.
</blockquote></details>

Elegant :) Fixed.
___
*[exabel_data_sdk/scripts/create_entity_mapping_from_csv.py, line 92 at r1](https://reviewable.io/reviews/exabel/python-sdk/17#-MSc1kgO8PCtpVAamji_:-MScCHm02NASgnB9peYx:b-pnhr4h) ([raw file](https://github.com/exabel/python-sdk/blob/8d66d9279ad667fc80a573e76f03d830b4a2a631/exabel_data_sdk/scripts/create_entity_mapping_from_csv.py#L92)):*
<details><summary><i>Previously, taral wrote…</i></summary><blockquote>

In this case we don’t produce anything useful, in which case I don’t think it is helpful to just produce an output file identical to the input file. Rather, raise an exception, e.g. `raise ValueError("The input file has no field named 'ticker'.")`. The exception might be caught in `run_script` and the error message output to the user.
</blockquote></details>

See below.
___
*[exabel_data_sdk/scripts/create_entity_mapping_from_csv.py, line 106 at r1](https://reviewable.io/reviews/exabel/python-sdk/17#-MSc2gCSBsqb1OyPmEgI:-MScCLUcBoJ68iU5pRIG:b-l191mp) ([raw file](https://github.com/exabel/python-sdk/blob/8d66d9279ad667fc80a573e76f03d830b4a2a631/exabel_data_sdk/scripts/create_entity_mapping_from_csv.py#L106)):*
<details><summary><i>Previously, taral wrote…</i></summary><blockquote>

`if "ticker" in mapping_input and "market" in mapping_input`

But I think it would be a bit clearer to do the opposite, and raise an exception if the input does not satisfy the requirements:

```
if "ticker" not in mapping_input or "market" not in mapping_input:
    raise ValueError("The input file must have fields named 'ticker' and 'market'.")
```
</blockquote></details>

I did it like this.
___
*[exabel_data_sdk/scripts/create_entity_mapping_from_csv.py, line 126 at r1](https://reviewable.io/reviews/exabel/python-sdk/17#-MSc40Ak4_4mKiPndPb0:-MScIKK0D6j61E4hy5gJ:bi3c0c4) ([raw file](https://github.com/exabel/python-sdk/blob/8d66d9279ad667fc80a573e76f03d830b4a2a631/exabel_data_sdk/scripts/create_entity_mapping_from_csv.py#L126)):*
<details><summary><i>Previously, taral wrote…</i></summary><blockquote>

This method returns a list of entities. For clarity, name this variable `entities`. We expect at most one entity to be returned, but I think we should verify that that is correct. If more than one entity is returned, we should emit a warning and not add any of them to the output.
</blockquote></details>

Agreed. I changed a bit here
___
*[exabel_data_sdk/scripts/create_entity_mapping_from_csv.py, line 144 at r1](https://reviewable.io/reviews/exabel/python-sdk/17#-MSc4hh27Od2B8gXWrTE:-MScJ2QWENXvDMLg8NNx:b-bybcdi) ([raw file](https://github.com/exabel/python-sdk/blob/8d66d9279ad667fc80a573e76f03d830b4a2a631/exabel_data_sdk/scripts/create_entity_mapping_from_csv.py#L144)):*
<details><summary><i>Previously, taral wrote…</i></summary><blockquote>

End the sentence with a period. Also, the ‘C’ in MIC stands for “code”, so just write “MICs” rather than “MIC codes”.
</blockquote></details>

Got me there :)

**Review by taral — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/exabel/python-sdk/17)* status: 3 of 4 files reviewed, 6 unresolved discussions (waiting on @blundski)

___
*[exabel_data_sdk/scripts/create_entity_mapping_from_csv.py, line 68 at r2](https://reviewable.io/reviews/exabel/python-sdk/17#-MScXTcP1Q13XXGrefo3:-MScXTcP1Q13XXGrefo4:bfs7gql) ([raw file](https://github.com/exabel/python-sdk/blob/bd939a32f3418807bb8a1c8771675ce48680ba09/exabel_data_sdk/scripts/create_entity_mapping_from_csv.py#L68)):*
> ```Python
>         )
> 
>     def get_entity_mapping(
> ```

This method doesn’t really do anything but call `get_entity_mapping_by_ticker` with the same arguments, so it is superfluous. I suppose it will be useful if we at some point support CSV files on a different format (e.g. with ISIN), but we aren’t currently going to support that, so I think we should just keep it simple and remove this method.
___
*[exabel_data_sdk/scripts/create_entity_mapping_from_csv.py, line 118 at r2](https://reviewable.io/reviews/exabel/python-sdk/17#-MScW2k52ScI4BIda8_y:-MScW2k52ScI4BIda8_z:b2wtoa) ([raw file](https://github.com/exabel/python-sdk/blob/bd939a32f3418807bb8a1c8771675ce48680ba09/exabel_data_sdk/scripts/create_entity_mapping_from_csv.py#L118)):*
> ```Python
>                     entity_type=args.entity_type, mic=market, ticker=ticker
>                 )
>                 if entities and len(entities) == 1:
> ```

`entities` cannot be `None` according to the type hint of `search_for_entities`, so you don’t need the guard clause. Just do `if len(entities) == 1`. 
___
*[exabel_data_sdk/scripts/create_entity_mapping_from_csv.py, line 122 at r2](https://reviewable.io/reviews/exabel/python-sdk/17#-MScaM0P7RxNdhlKkZeX:-MScaM0P7RxNdhlKkZeY:brhumzt) ([raw file](https://github.com/exabel/python-sdk/blob/bd939a32f3418807bb8a1c8771675ce48680ba09/exabel_data_sdk/scripts/create_entity_mapping_from_csv.py#L122)):*
> ```Python
>                     found = True
>                     break
>                 elif entities and len(entities) > 1:
> ```

Same here.
___
*[exabel_data_sdk/scripts/create_entity_mapping_from_csv.py, line 126 at r2](https://reviewable.io/reviews/exabel/python-sdk/17#-MScWdp1AsOvsm5ZwBYG:-MScWdp1AsOvsm5ZwBYH:bqdnadr) ([raw file](https://github.com/exabel/python-sdk/blob/bd939a32f3418807bb8a1c8771675ce48680ba09/exabel_data_sdk/scripts/create_entity_mapping_from_csv.py#L126)):*
> ```Python
>                         f"Found {len(entities)} entities when searching for {ticker} on market {market} - dropping from mapping"
>                     )
>                     mapping_output = mapping_output.drop(index=i)
> ```

This will happen if you simply drop `found = True`.
___
*[exabel_data_sdk/scripts/create_entity_mapping_from_csv.py, line 157 at r2](https://reviewable.io/reviews/exabel/python-sdk/17#-MScZufwBujm9-oX1Gs_:-MScZufwBujm9-oX1Gsa:b-14074o) ([raw file](https://github.com/exabel/python-sdk/blob/bd939a32f3418807bb8a1c8771675ce48680ba09/exabel_data_sdk/scripts/create_entity_mapping_from_csv.py#L157)):*
> ```Python
>             mapping_output = self.get_entity_mapping(client, args, mapping_input)
>         except ValueError as error:
>             raise
> ```

This has no effect compared to not catching the exception at all. In this case the only purpose of catching the exception would be to output the error message in a nicer way. I suggest you print the error message and do not reraise the exception.
___
*[exabel_data_sdk/scripts/create_entity_mapping_from_csv.py, line 159 at r2](https://reviewable.io/reviews/exabel/python-sdk/17#-MSc_uGx3cVakTr-pOhx:-MSc_uGx3cVakTr-pOhy:bfqd0aq) ([raw file](https://github.com/exabel/python-sdk/blob/bd939a32f3418807bb8a1c8771675ce48680ba09/exabel_data_sdk/scripts/create_entity_mapping_from_csv.py#L159)):*
> ```Python
>             raise
> 
>         mapping_output.to_csv(args.filename_output, sep=args.sep, index=False)
> ```

Move this to inside the `try` block.

**Review by blundski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/exabel/python-sdk/17)* status: 2 of 5 files reviewed, 6 unresolved discussions (waiting on @taral)

___
*[exabel_data_sdk/scripts/create_entity_mapping_from_csv.py, line 68 at r2](https://reviewable.io/reviews/exabel/python-sdk/17#-MScXTcP1Q13XXGrefo3:-MScdYZDEIasjtbO8SAH:b-v0brrc) ([raw file](https://github.com/exabel/python-sdk/blob/bd939a32f3418807bb8a1c8771675ce48680ba09/exabel_data_sdk/scripts/create_entity_mapping_from_csv.py#L68)):*
<details><summary><i>Previously, taral wrote…</i></summary><blockquote>

This method doesn’t really do anything but call `get_entity_mapping_by_ticker` with the same arguments, so it is superfluous. I suppose it will be useful if we at some point support CSV files on a different format (e.g. with ISIN), but we aren’t currently going to support that, so I think we should just keep it simple and remove this method.
</blockquote></details>

I wanted to keep it as a placeholder for further entity mappings but ok - removing
___
*[exabel_data_sdk/scripts/create_entity_mapping_from_csv.py, line 118 at r2](https://reviewable.io/reviews/exabel/python-sdk/17#-MScW2k52ScI4BIda8_y:-MSce8zSDSWMzr1wyblO:b-ccio33) ([raw file](https://github.com/exabel/python-sdk/blob/bd939a32f3418807bb8a1c8771675ce48680ba09/exabel_data_sdk/scripts/create_entity_mapping_from_csv.py#L118)):*
<details><summary><i>Previously, taral wrote…</i></summary><blockquote>

`entities` cannot be `None` according to the type hint of `search_for_entities`, so you don’t need the guard clause. Just do `if len(entities) == 1`. 
</blockquote></details>

Too much Java - done
___
*[exabel_data_sdk/scripts/create_entity_mapping_from_csv.py, line 122 at r2](https://reviewable.io/reviews/exabel/python-sdk/17#-MScaM0P7RxNdhlKkZeX:-MSceJ0_8XM8xroUB9t5:b-89a4l7) ([raw file](https://github.com/exabel/python-sdk/blob/bd939a32f3418807bb8a1c8771675ce48680ba09/exabel_data_sdk/scripts/create_entity_mapping_from_csv.py#L122)):*
<details><summary><i>Previously, taral wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

Ditto
___
*[exabel_data_sdk/scripts/create_entity_mapping_from_csv.py, line 126 at r2](https://reviewable.io/reviews/exabel/python-sdk/17#-MScWdp1AsOvsm5ZwBYG:-MScehfs5948WLTk-y_p:b-fzzohq) ([raw file](https://github.com/exabel/python-sdk/blob/bd939a32f3418807bb8a1c8771675ce48680ba09/exabel_data_sdk/scripts/create_entity_mapping_from_csv.py#L126)):*
<details><summary><i>Previously, taral wrote…</i></summary><blockquote>

This will happen if you simply drop `found = True`.
</blockquote></details>

I didn't get that? I wanted different messages on the cases: 
- found more than 1 entity
- found no entity
___
*[exabel_data_sdk/scripts/create_entity_mapping_from_csv.py, line 157 at r2](https://reviewable.io/reviews/exabel/python-sdk/17#-MScZufwBujm9-oX1Gs_:-MScfM68CZ4XEY4HMLSL:bp1oj4) ([raw file](https://github.com/exabel/python-sdk/blob/bd939a32f3418807bb8a1c8771675ce48680ba09/exabel_data_sdk/scripts/create_entity_mapping_from_csv.py#L157)):*
<details><summary><i>Previously, taral wrote…</i></summary><blockquote>

This has no effect compared to not catching the exception at all. In this case the only purpose of catching the exception would be to output the error message in a nicer way. I suggest you print the error message and do not reraise the exception.
</blockquote></details>

Reraising the exception is how I unittest wrong fileformat. Print *and* reraise?
___
*[exabel_data_sdk/scripts/create_entity_mapping_from_csv.py, line 159 at r2](https://reviewable.io/reviews/exabel/python-sdk/17#-MSc_uGx3cVakTr-pOhx:-MScgWZxC5RbMSZ6bhel:b-gg6jxi) ([raw file](https://github.com/exabel/python-sdk/blob/bd939a32f3418807bb8a1c8771675ce48680ba09/exabel_data_sdk/scripts/create_entity_mapping_from_csv.py#L159)):*
<details><summary><i>Previously, taral wrote…</i></summary><blockquote>

Move this to inside the `try` block.
</blockquote></details>

Done.

I also re-introduced the "dry-run" parameter as I do not want the unittests to produce output file. Is that ok?

**Review by taral — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/exabel/python-sdk/17)* status: 2 of 5 files reviewed, 5 unresolved discussions (waiting on @blundski and @taral)

___
*[exabel_data_sdk/scripts/create_entity_mapping_from_csv.py, line 126 at r2](https://reviewable.io/reviews/exabel/python-sdk/17#-MScWdp1AsOvsm5ZwBYG:-MScpvgh0KQNxkqOWspG:b-ounkl5) ([raw file](https://github.com/exabel/python-sdk/blob/bd939a32f3418807bb8a1c8771675ce48680ba09/exabel_data_sdk/scripts/create_entity_mapping_from_csv.py#L126)):*
<details><summary><i>Previously, blundski wrote…</i></summary><blockquote>

I didn't get that? I wanted different messages on the cases: 
- found more than 1 entity
- found no entity
</blockquote></details>

Ok, then it’s fine.
___
*[exabel_data_sdk/scripts/create_entity_mapping_from_csv.py, line 157 at r2](https://reviewable.io/reviews/exabel/python-sdk/17#-MScZufwBujm9-oX1Gs_:-MScqdgbAyTPoJtS3CnR:b-j9nmdw) ([raw file](https://github.com/exabel/python-sdk/blob/bd939a32f3418807bb8a1c8771675ce48680ba09/exabel_data_sdk/scripts/create_entity_mapping_from_csv.py#L157)):*
<details><summary><i>Previously, blundski wrote…</i></summary><blockquote>

Reraising the exception is how I unittest wrong fileformat. Print *and* reraise?
</blockquote></details>

Both printing and raising isn’t necessary, because the error message will be printed to the terminal as part of the stack trace if you let the exception escape.

My main point was that there is no point in catching the exception and then do nothing but raise it again. You might as well not catch it.

That is,

```
try:
    mapping_output = self.get_entity_mapping_by_ticker(client, args, mapping_input)
except ValueError:
    raise
```
is equivalent to just
```
mapping_output = self.get_entity_mapping_by_ticker(client, args, mapping_input)
```

For testing purposes, one option is to put that functionality into a separate method and test that method, and then let `run_script` just call the other method and handle the exceptions. (That’s only necessary if we want the script to fail gracefully. It’s not very important.)
___
*[exabel_data_sdk/scripts/create_entity_mapping_from_csv.py, line 159 at r2](https://reviewable.io/reviews/exabel/python-sdk/17#-MSc_uGx3cVakTr-pOhx:-MScspw6CRs0cxn2KvTs:b-ff6zxk) ([raw file](https://github.com/exabel/python-sdk/blob/bd939a32f3418807bb8a1c8771675ce48680ba09/exabel_data_sdk/scripts/create_entity_mapping_from_csv.py#L159)):*
<details><summary><i>Previously, blundski wrote…</i></summary><blockquote>

Done.

I also re-introduced the "dry-run" parameter as I do not want the unittests to produce output file. Is that ok?
</blockquote></details>

I don’t think I like arguments that are exposed just for the benefit of tests.

One option is to write to a temporary file, which is automatically cleaned up:

```
import tempfile

with tempfile.TemporaryDirectory() as tmp:
    output_file = f"{tmp}/output.csv"
    ...
```
___
*[exabel_data_sdk/scripts/create_entity_mapping_from_csv.py, line 153 at r3](https://reviewable.io/reviews/exabel/python-sdk/17#-MScqZ5l9ggUqyDpacEl:-MScqZ5l9ggUqyDpacEm:b-lv6dym) ([raw file](https://github.com/exabel/python-sdk/blob/c15d87462568b4710a2188e33529af11e688277c/exabel_data_sdk/scripts/create_entity_mapping_from_csv.py#L153)):*
> ```Python
>                 mapping_output.to_csv(args.filename_output, sep=args.sep, index=False)
>         except ValueError as error:
>             print(str(error))
> ```

`print(str(error))` has the same effect as the simpler `print(error)`.

**Review by blundski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/exabel/python-sdk/17)* status: 2 of 5 files reviewed, 5 unresolved discussions (waiting on @taral)

___
*[exabel_data_sdk/scripts/create_entity_mapping_from_csv.py, line 157 at r2](https://reviewable.io/reviews/exabel/python-sdk/17#-MScZufwBujm9-oX1Gs_:-MSd4f_E012ZW4vT4s7k:b-1bv2cs) ([raw file](https://github.com/exabel/python-sdk/blob/bd939a32f3418807bb8a1c8771675ce48680ba09/exabel_data_sdk/scripts/create_entity_mapping_from_csv.py#L157)):*
<details><summary><i>Previously, taral wrote…</i></summary><blockquote>

Both printing and raising isn’t necessary, because the error message will be printed to the terminal as part of the stack trace if you let the exception escape.

My main point was that there is no point in catching the exception and then do nothing but raise it again. You might as well not catch it.

That is,

```
try:
    mapping_output = self.get_entity_mapping_by_ticker(client, args, mapping_input)
except ValueError:
    raise
```
is equivalent to just
```
mapping_output = self.get_entity_mapping_by_ticker(client, args, mapping_input)
```

For testing purposes, one option is to put that functionality into a separate method and test that method, and then let `run_script` just call the other method and handle the exceptions. (That’s only necessary if we want the script to fail gracefully. It’s not very important.)
</blockquote></details>

Creating a separate method means coupling this line from run_script:

        mapping_input = pd.read_csv(args.filename_input, header=0, sep=args.sep)

together with this line from get_entity_mapping_by_ticker:

        if "ticker" not in mapping_input or "market" not in mapping_input:
            raise ValueError("The input file must have fields named 'ticker' and 'market'.")

This smells a bit to me as we want to keep the sanity tests on input in separate methods if we want to expand on id's we can handle.

Then I'd rather just remove the test - it basically just test the latter line depending on reading the file input. It makes more sense to have it if we have several sanity tests we want to check
___
*[exabel_data_sdk/scripts/create_entity_mapping_from_csv.py, line 159 at r2](https://reviewable.io/reviews/exabel/python-sdk/17#-MSc_uGx3cVakTr-pOhx:-MSd4M2D98dxqhGY8-3e:b-13u5c8) ([raw file](https://github.com/exabel/python-sdk/blob/bd939a32f3418807bb8a1c8771675ce48680ba09/exabel_data_sdk/scripts/create_entity_mapping_from_csv.py#L159)):*
<details><summary><i>Previously, taral wrote…</i></summary><blockquote>

I don’t think I like arguments that are exposed just for the benefit of tests.

One option is to write to a temporary file, which is automatically cleaned up:

```
import tempfile

with tempfile.TemporaryDirectory() as tmp:
    output_file = f"{tmp}/output.csv"
    ...
```
</blockquote></details>

That's a nice feature I haven't seen before - I got it working locally
___
*[exabel_data_sdk/scripts/create_entity_mapping_from_csv.py, line 153 at r3](https://reviewable.io/reviews/exabel/python-sdk/17#-MScqZ5l9ggUqyDpacEl:-MSczWWf0d4HqNgLD8tt:b-896fix) ([raw file](https://github.com/exabel/python-sdk/blob/c15d87462568b4710a2188e33529af11e688277c/exabel_data_sdk/scripts/create_entity_mapping_from_csv.py#L153)):*
<details><summary><i>Previously, taral wrote…</i></summary><blockquote>

`print(str(error))` has the same effect as the simpler `print(error)`.
</blockquote></details>

Done.

**Review by taral — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 3 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/exabel/python-sdk/17#-:-MSg4hSf7V3hTRVpaKzP:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by blundski — COMMENTED** [review]
Takk!

> *[Reviewable](https://reviewable.io/reviews/exabel/python-sdk/17#-:-MSg5kxY1iDh7GON5cNZ:b-80mpxt)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
