### PR TITLE
Support JSON requests over HTTP

### PR DESCRIPTION
**Pull request by taral**
This change is [Reviewable](https://reviewable.io/reviews/exabel/python-sdk/28)

### CODE REVIEW

**Review by burk — APPROVED** [review]
> Reviewed 43 of 43 files at r1.
> *[Reviewable](https://reviewable.io/reviews/exabel/python-sdk/28)* status: all files reviewed, 4 unresolved discussions (waiting on @taral)

___
*[exabel_data_sdk/client/api/error_handler.py, line 46 at r1](https://reviewable.io/reviews/exabel/python-sdk/28#-McyMM9z2QiAVSQfkMO7:-McyMMA-497FAFvRlumF:b-dvgmpy) ([raw file](https://github.com/exabel/python-sdk/blob/c484e0eda169cbedf04d8fe9356e9fe9bc5b71d7/exabel_data_sdk/client/api/error_handler.py#L46)):*
> ```Python
>     if status_code == HTTPStatus.SERVICE_UNAVAILABLE:
>         return ErrorType.UNAVAILABLE
>     if status_code == HTTPStatus.GATEWAY_TIMEOUT:
> ```

(there are some more here: https://github.com/cloudendpoints/esp/blob/master/src/api_manager/utils/status.cc#L320 but I don't know if they are required)
___
*[exabel_data_sdk/client/api/api_client/http/base_http_client.py, line 31 at r1](https://reviewable.io/reviews/exabel/python-sdk/28#-McyN2ha9P7YE5R_gaBM:-McyN2ha9P7YE5R_gaBN:bee1ogk) ([raw file](https://github.com/exabel/python-sdk/blob/c484e0eda169cbedf04d8fe9356e9fe9bc5b71d7/exabel_data_sdk/client/api/api_client/http/base_http_client.py#L31)):*
> ```Python
>     @overload
>     def _request(self, method: str, url: str, response_proto: None, body: Message = None) -> None:
>         ...
> ```

Oh, I haven't seen this before. Cool!
___
*[exabel_data_sdk/client/api/api_client/http/relationship_http_client.py, line 48 at r1](https://reviewable.io/reviews/exabel/python-sdk/28#-McyNfBcCo2r85OINil-:-McyNfBcCo2r85OINil0:b-wulyvc) ([raw file](https://github.com/exabel/python-sdk/blob/c484e0eda169cbedf04d8fe9356e9fe9bc5b71d7/exabel_data_sdk/client/api/api_client/http/relationship_http_client.py#L48)):*
> ```Python
>     def get_relationship(self, request: GetRelationshipRequest) -> Relationship:
>         # Since GetRelationship has the same url as ListRelationships, these requests cannot be
>         # distinguished by the server, and we get a ListRelationshipsResponse.
> ```

(Sounds like a bug in the REST mapping)
___
*[exabel_data_sdk/client/api/data_classes/signal.py, line 25 at r1](https://reviewable.io/reviews/exabel/python-sdk/28#-McyO4Fd7EQBT5m_17f1:-McyO4Fd7EQBT5m_17f2:bt12wdd) ([raw file](https://github.com/exabel/python-sdk/blob/0946bbc799af4f0824c162f16e2025b790543036/exabel_data_sdk/client/api/data_classes/signal.py#L25)):*
> ```Python
>         self,
>         name: str,
>         entity_type: str,
> ```

(would it be better to deprecate it but leave it with a default value of None to not break existing code? I guess it's not so important as we're our biggest user ourselves..)

**Review by burk — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/exabel/python-sdk/28)* status: all files reviewed, 4 unresolved discussions (waiting on @taral)

___
*[exabel_data_sdk/client/api/api_client/http/base_http_client.py, line 31 at r1](https://reviewable.io/reviews/exabel/python-sdk/28#-McyN2ha9P7YE5R_gaBM:-McyOlHgDYyggijnmEMM:b5q0iiw) ([raw file](https://github.com/exabel/python-sdk/blob/c484e0eda169cbedf04d8fe9356e9fe9bc5b71d7/exabel_data_sdk/client/api/api_client/http/base_http_client.py#L31)):*
<details><summary><i>Previously, burk (Bjørn Rustad) wrote…</i></summary><blockquote>

Oh, I haven't seen this before. Cool!
</blockquote></details>

In the example on the webpage, the actual implementation of the method has no type annotation at all though?

**Review by taral — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/exabel/python-sdk/28)* status: all files reviewed, 4 unresolved discussions (waiting on @burk)

___
*[exabel_data_sdk/client/api/error_handler.py, line 46 at r1](https://reviewable.io/reviews/exabel/python-sdk/28#-McyMM9z2QiAVSQfkMO7:-McyPIop7G5VcN4r8SPM:brbt4b8) ([raw file](https://github.com/exabel/python-sdk/blob/c484e0eda169cbedf04d8fe9356e9fe9bc5b71d7/exabel_data_sdk/client/api/error_handler.py#L46)):*
<details><summary><i>Previously, burk (Bjørn Rustad) wrote…</i></summary><blockquote>

(there are some more here: https://github.com/cloudendpoints/esp/blob/master/src/api_manager/utils/status.cc#L320 but I don't know if they are required)
</blockquote></details>

I selected the error codes that I see we use in the Data API server, so I think this is sufficient.
___
*[exabel_data_sdk/client/api/api_client/http/base_http_client.py, line 31 at r1](https://reviewable.io/reviews/exabel/python-sdk/28#-McyN2ha9P7YE5R_gaBM:-McyPol0A3V3oAXbcACK:bgdepec) ([raw file](https://github.com/exabel/python-sdk/blob/c484e0eda169cbedf04d8fe9356e9fe9bc5b71d7/exabel_data_sdk/client/api/api_client/http/base_http_client.py#L31)):*
<details><summary><i>Previously, burk (Bjørn Rustad) wrote…</i></summary><blockquote>

In the example on the webpage, the actual implementation of the method has no type annotation at all though?
</blockquote></details>

Mypy complains if I remove them.
___
*[exabel_data_sdk/client/api/api_client/http/relationship_http_client.py, line 48 at r1](https://reviewable.io/reviews/exabel/python-sdk/28#-McyNfBcCo2r85OINil-:-McyPrHgElsiQE7qNJn9:b-f6twnz) ([raw file](https://github.com/exabel/python-sdk/blob/c484e0eda169cbedf04d8fe9356e9fe9bc5b71d7/exabel_data_sdk/client/api/api_client/http/relationship_http_client.py#L48)):*
<details><summary><i>Previously, burk (Bjørn Rustad) wrote…</i></summary><blockquote>

(Sounds like a bug in the REST mapping)
</blockquote></details>

Yes, the proto method definition is accompanied by a TODO.
___
*[exabel_data_sdk/client/api/data_classes/signal.py, line 25 at r1](https://reviewable.io/reviews/exabel/python-sdk/28#-McyO4Fd7EQBT5m_17f1:-McyQ0cE2zGS8tSxWmTY:b-i57jhp) ([raw file](https://github.com/exabel/python-sdk/blob/0946bbc799af4f0824c162f16e2025b790543036/exabel_data_sdk/client/api/data_classes/signal.py#L25)):*
<details><summary><i>Previously, burk (Bjørn Rustad) wrote…</i></summary><blockquote>

(would it be better to deprecate it but leave it with a default value of None to not break existing code? I guess it's not so important as we're our biggest user ourselves..)
</blockquote></details>

It’s a bit awkward to deprecate the second argument in a list of four mandatory arguments. Since the fix is just to remove an argument, I don’t think it is a great burden on clients to make the change right away.

**Review by burk — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/exabel/python-sdk/28)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[exabel_data_sdk/client/api/data_classes/signal.py, line 25 at r1](https://reviewable.io/reviews/exabel/python-sdk/28#-McyO4Fd7EQBT5m_17f1:-McyYQc_0NSFSm6yqSa6:b-1ujfa8) ([raw file](https://github.com/exabel/python-sdk/blob/0946bbc799af4f0824c162f16e2025b790543036/exabel_data_sdk/client/api/data_classes/signal.py#L25)):*
<details><summary><i>Previously, taral wrote…</i></summary><blockquote>

It’s a bit awkward to deprecate the second argument in a list of four mandatory arguments. Since the fix is just to remove an argument, I don’t think it is a great burden on clients to make the change right away.
</blockquote></details>

Ah, true.

**Pull request merged**
