### PR TITLE
add support for id types in entity mapping

### PR DESCRIPTION
**Pull request by blundski**
This change is [Reviewable](https://reviewable.io/reviews/exabel/python-sdk/21)

### CODE REVIEW

**Comment by blundski** [comment]
This should add support for isin, factset_identity and bloomberg_ticker to the entity mapping by csv method.

Comments welcome.

**Review by taral — CHANGES_REQUESTED** [review]
> Reviewed 3 of 6 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/exabel/python-sdk/21)* status: 4 of 6 files reviewed, 3 unresolved discussions (waiting on @blundski)

___
*[exabel_data_sdk/scripts/create_entity_mapping_from_csv.py, line 108 at r2](https://reviewable.io/reviews/exabel/python-sdk/21#-MbB3v00CfB6Plp_fwHP:-MbB3v00CfB6Plp_fwHQ:b1ogioj) ([raw file](https://github.com/exabel/python-sdk/blob/c57506dc1c8531e8f1e526545ca50c478838a6b9/exabel_data_sdk/scripts/create_entity_mapping_from_csv.py#L108)):*
> ```Python
>             return self._get_entity_mapping_by_id(
>                 client, args.entity_type, "bloomberg_ticker", mapping_input
>             )
> ```

The last three ifs contain much repetition. One alternative is something like
```
identifier = next((column for column in mapping_input if column in {"isin", "factset_identifier", "bloomberg_ticker"}), None)
if identifier is not None:
    return self._get_entity_mapping_by_id(client, args.entity_type, identifier, mapping_input)
```
___
*[tests/resources/data/mapping_factset_identifier.csv, line 3 at r2](https://reviewable.io/reviews/exabel/python-sdk/21#-MbBBhfE4xMTzZgY1m35:-MbBBhfE4xMTzZgY1m36:b-trwhjr) ([raw file](https://github.com/exabel/python-sdk/blob/c57506dc1c8531e8f1e526545ca50c478838a6b9/tests/resources/data/mapping_factset_identifier.csv#L3)):*
> ```CSV
> factset_identifier
> 0MXNWD-E
> DT699H-S
> ```

Missing newline at end of file. (By convention all text files should end with a newline.)
___
*[tests/resources/data/mapping_isin.csv, line 2 at r2](https://reviewable.io/reviews/exabel/python-sdk/21#-MbBBjZc8eTRQzhxHu2P:-MbBBjZc8eTRQzhxHu2Q:b-de60hc) ([raw file](https://github.com/exabel/python-sdk/blob/c57506dc1c8531e8f1e526545ca50c478838a6b9/tests/resources/data/mapping_isin.csv#L2)):*
> ```CSV
> isin
> NO0010096985
> ```

Missing newline at end of file.

**Review by blundski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/exabel/python-sdk/21)* status: 3 of 6 files reviewed, 3 unresolved discussions (waiting on @taral)

___
*[exabel_data_sdk/scripts/create_entity_mapping_from_csv.py, line 108 at r2](https://reviewable.io/reviews/exabel/python-sdk/21#-MbB3v00CfB6Plp_fwHP:-MbBJhhS6wXGO66mkvWX:b-896fix) ([raw file](https://github.com/exabel/python-sdk/blob/c57506dc1c8531e8f1e526545ca50c478838a6b9/exabel_data_sdk/scripts/create_entity_mapping_from_csv.py#L108)):*
<details><summary><i>Previously, taral wrote…</i></summary><blockquote>

The last three ifs contain much repetition. One alternative is something like
```
identifier = next((column for column in mapping_input if column in {"isin", "factset_identifier", "bloomberg_ticker"}), None)
if identifier is not None:
    return self._get_entity_mapping_by_id(client, args.entity_type, identifier, mapping_input)
```
</blockquote></details>

Done.
___
*[tests/resources/data/mapping_factset_identifier.csv, line 3 at r2](https://reviewable.io/reviews/exabel/python-sdk/21#-MbBBhfE4xMTzZgY1m35:-MbBJiYM7GCkyjGnCLFi:b-896fix) ([raw file](https://github.com/exabel/python-sdk/blob/c57506dc1c8531e8f1e526545ca50c478838a6b9/tests/resources/data/mapping_factset_identifier.csv#L3)):*
<details><summary><i>Previously, taral wrote…</i></summary><blockquote>

Missing newline at end of file. (By convention all text files should end with a newline.)
</blockquote></details>

Done.
___
*[tests/resources/data/mapping_isin.csv, line 2 at r2](https://reviewable.io/reviews/exabel/python-sdk/21#-MbBBjZc8eTRQzhxHu2P:-MbBJj1X61_ri_6nlEBX:b-896fix) ([raw file](https://github.com/exabel/python-sdk/blob/c57506dc1c8531e8f1e526545ca50c478838a6b9/tests/resources/data/mapping_isin.csv#L2)):*
<details><summary><i>Previously, taral wrote…</i></summary><blockquote>

Missing newline at end of file.
</blockquote></details>

Done.

**Review by taral — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/exabel/python-sdk/21#-:-MbBK39A1lH961X_MjW8:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
