### PR TITLE
Support Python 3.6

### PR DESCRIPTION
**Pull request by taral**
Creates a Pipfile and a Docker image with Python 3.6 in order to test the sdk in an appropriate environment.

---
This change is [Reviewable](https://reviewable.io/reviews/exabel/python-sdk/13)

### CODE REVIEW

**Comment by bnordli** [comment]
___
*[Jenkinsfile, line 129 at r1](https://reviewable.io/reviews/exabel/python-sdk/13#-MRToFjI2QjaELpEAiNu:-MRToFjI2QjaELpEAiNv:b-8o5ybb) ([raw file](https://github.com/exabel/python-sdk/blob/71fbcf6fcd4bc9808b8d05381e9c1e1274c6d659/Jenkinsfile#L129)):*
> ```Groovy
> 
>       if (buildLevel >= BUILD_PUBLISH) {
>         container('python') {
> ```

This tells Jenkins what container to run in. You need to copy the `jnlp` containerTemplate from the main repo and run it inside that one. (And since everything python runs inside that container, you don't need the `python` container anymore :)

**Review by taral — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/exabel/python-sdk/13)* status: Pipfile.lock ignored, 1 of 5 files reviewed, 1 unresolved discussion (waiting on @bnordli)

___
*[Jenkinsfile, line 129 at r1](https://reviewable.io/reviews/exabel/python-sdk/13#-MRToFjI2QjaELpEAiNu:-MRU7_cS8c926fx2gjQk:b-896fix) ([raw file](https://github.com/exabel/python-sdk/blob/71fbcf6fcd4bc9808b8d05381e9c1e1274c6d659/Jenkinsfile#L129)):*
<details><summary><i>Previously, bnordli (Børge Nordli) wrote…</i></summary><blockquote>

This tells Jenkins what container to run in. You need to copy the `jnlp` containerTemplate from the main repo and run it inside that one. (And since everything python runs inside that container, you don't need the `python` container anymore :)
</blockquote></details>

Done.

**Review by bnordli — APPROVED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/exabel/python-sdk/13)* status: :shipit: complete! Pipfile.lock ignored, all files reviewed, all discussions resolved

**Review by hallarak — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/exabel/python-sdk/13#-:-MRUQJOt207vg2Otz7g8:bnfp4nl)* status: :shipit: complete! Pipfile.lock ignored, all files reviewed, all discussions resolved

**Pull request merged**
