### PR TITLE
Add GitHub Actions workflow for automated PyPI deployment

### PR DESCRIPTION
**Pull request by aksestok**
When a new release is published:
* Validate that VERSION has been set correctly (same as the git tag).
* Build and test the package.
* Install the package for all supported python versions and rerun unit tests.
* Publish the package to PyPI.

---
This change is [Reviewable](https://reviewable.io/reviews/exabel/python-sdk/42)

### CODE REVIEW

**Comment by aksestok** [comment]
[Setup deployment from exabel to python-sdk public repo](https://trello.com/c/Blzymntn/2955-setup-deployment-from-exabel-to-python-sdk-public-repo)

**Review by taral — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/exabel/python-sdk/42)* status: all files reviewed, 1 unresolved discussion (waiting on @aksestok)

___
*[.github/workflows/publish.yml, line 63 at r2](https://reviewable.io/reviews/exabel/python-sdk/42#-MjTFtFt-qbazLgjHIpm:-MjTFtFt-qbazLgjHIpn:bgsnilb) ([raw file](https://github.com/exabel/python-sdk/blob/bc80c9d8afde0dee9881489dafd0bcd5519dca1e/.github/workflows/publish.yml#L63)):*
> ```YAML
>         PACKAGE=$(ls ./dist/ | grep -P .+\.whl$)
>         pip install ./dist/$PACKAGE
>     
> ```

A line with only spaces.

**Review by aksestok — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/exabel/python-sdk/42)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @taral)

___
*[.github/workflows/publish.yml, line 63 at r2](https://reviewable.io/reviews/exabel/python-sdk/42#-MjTFtFt-qbazLgjHIpm:-MjTIJCe34_vf8mtwxxG:b-896fix) ([raw file](https://github.com/exabel/python-sdk/blob/bc80c9d8afde0dee9881489dafd0bcd5519dca1e/.github/workflows/publish.yml#L63)):*
<details><summary><i>Previously, taral wrote…</i></summary><blockquote>

A line with only spaces.
</blockquote></details>

Done.

**Review by taral — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/exabel/python-sdk/42#-:-MjTIQm13RtamiCSrbth:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
