### PR TITLE
add import service for entities and relationships

### PR DESCRIPTION
**Pull request by blundski**
This change is [Reviewable](https://reviewable.io/reviews/exabel/python-sdk/40)

### CODE REVIEW

**Review by taral — COMMENTED** [review]
The `__init__.py` files should not be deleted. (There’s a shortcoming in the stub generation script, which we’ll have to fix. For now, just add them back.)

> Reviewed 9 of 18 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/exabel/python-sdk/40#-:-MjErqsF3ArVa_zCfW28:b-vbnpc5)* status: 9 of 18 files reviewed, all discussions resolved

**Review by blundski — COMMENTED** [review]
Ouch. Done.

> *[Reviewable](https://reviewable.io/reviews/exabel/python-sdk/40#-:-MjEuQPD6WTRilrw83iT:b-t4f506)* status: 9 of 18 files reviewed, all discussions resolved

**Review by taral — APPROVED** [review]
> Reviewed 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/exabel/python-sdk/40)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by taral — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/exabel/python-sdk/40)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by taral — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/exabel/python-sdk/40)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
