### PR TITLE
Post status to Slack

### PR DESCRIPTION
**Pull request by oyvindwe**
This change is [Reviewable](https://reviewable.io/reviews/exabel/python-sdk/128)

### CODE REVIEW

**Review by aksestok — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/exabel/python-sdk/128)* status: all files reviewed, 2 unresolved discussions (waiting on @oyvindwe)

*[a discussion](https://reviewable.io/reviews/exabel/python-sdk/128#-NAdKbcq2rJmCuJh14dm:-NAdKbcq2rJmCuJh14dn:bv4db9g) (no related file):*
We also want to post if [publish.yml](https://github.com/Exabel/python-sdk/blob/main/.github/workflows/publish.yml) succeeds/fails?

___
___
*[`.github/workflows/test_installability.yml` line 36 at r1](https://reviewable.io/reviews/exabel/python-sdk/128#-NAdL1Dk2pQeX9EEGExa:-NAdKO6F8unNU1xi7_ze:b-np53ct) ([raw file](https://github.com/exabel/python-sdk/blob/6ccec4cea9a469fec2571f9cfb7e4645ac70f431/.github/workflows/test_installability.yml#L36)):*
> ```YAML
>     - name: Post to Slack
>       uses: ravsamhq/notify-slack-action@v2
>       if: always()
> ```

We only want to be notified if it fails?



_Suggestion:_
```YAML
      if: failure()
```

**Review by oyvindwe — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/exabel/python-sdk/128)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @aksestok)

*[a discussion](https://reviewable.io/reviews/exabel/python-sdk/128#-NAdKbcq2rJmCuJh14dm:-NAdiY4F05UIEJoRB9rY:b-896fix) (no related file):*
<details><summary><i>Previously, aksestok (Aksel Stokseth) wrote…</i></summary><blockquote>

We also want to post if [publish.yml](https://github.com/Exabel/python-sdk/blob/main/.github/workflows/publish.yml) succeeds/fails?
</blockquote></details>

Done.

___
___
*[`.github/workflows/test_installability.yml` line 36 at r1](https://reviewable.io/reviews/exabel/python-sdk/128#-NAdL1Dk2pQeX9EEGExa:-NAdi_aS-DSqwe9Y612p:b-896fix) ([raw file](https://github.com/exabel/python-sdk/blob/6ccec4cea9a469fec2571f9cfb7e4645ac70f431/.github/workflows/test_installability.yml#L36)):*
<details><summary><i>Previously, aksestok (Aksel Stokseth) wrote…</i></summary><blockquote>

We only want to be notified if it fails?
</blockquote></details>

Done.

**Review by oyvindwe — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/exabel/python-sdk/128)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`.github/workflows/test_installability.yml` line 36 at r1](https://reviewable.io/reviews/exabel/python-sdk/128#-NAdL1Dk2pQeX9EEGExa:-NAduTIfE8HpEK_tL6Yl:b-f81ude) ([raw file](https://github.com/exabel/python-sdk/blob/6ccec4cea9a469fec2571f9cfb7e4645ac70f431/.github/workflows/test_installability.yml#L36)):*
<details><summary><i>Previously, aksestok (Aksel Stokseth) wrote…</i></summary><blockquote>

Since the strategy for this job is a matrix, we will send up to 4 messages if tests fail. This is as intended?
</blockquote></details>

Fail fast is enabled, so we should only get one, unless two jobs fails simultaneously.

**Review by aksestok — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/exabel/python-sdk/128#-:-NAe2hYL1FihfcuOCKrX:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by aksestok — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/exabel/python-sdk/128)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
