### PR TITLE
Release v4.1.0

### PR DESCRIPTION
**Pull request by ivarurdalen**
# Added
- Support for data export from AWS Athena.
- Batched query support in ExportAPI.
- Support for TagService in AnalyticsAPI.
- GCP Service Account credentials can be specified as string with `--credentials-string` argument
- `ExportAPI.signal_query` now has the ability to specify resource_names.
- New method in relationship_api to list all relationships of a given type.
- All pageable list methods now have an equivalent utility method `get_<resource>_iterator` which can be called to get an iterator that can page through all available resources. E.g. `list(client.entity_api.get_entity_type_iterator())`.
- `--skip-validation` argument to time series loaders to avoid validation if set. Can speed up reading of time series from file, if the input file is pre-validated.
- Support batch upload for all resource types. New argument `--batch-size` specifies how many data rows to include per batch.
- Allow timeseries to be loaded to the global entity (`entityTypes/global/entities/global`).

# Changed
- Default login timeout for Snowflake connections set to 15 secs.
- Default timeout for API requests in the client set to 15 mins.
- Max metadata size for gRPC headers increased to 16MB.
- Multiple user tokens can now be stored locally when using the ExportAPI with the new `--user` argument.

# Fixed
- Improvements for faster parsing of time series in file upload.
- General improvements to logging to remove noise.

- - -
This change is [Reviewable](https://reviewable.io/reviews/Exabel/python-sdk/137)

### CODE REVIEW

**Review by aksestok — CHANGES_REQUESTED** [review]
> Reviewed 175 of 175 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Exabel/python-sdk/137)* status: Pipfile.lock ignored, all files reviewed, 1 unresolved discussion (waiting on @ivarurdalen)

*[a discussion](https://reviewable.io/reviews/Exabel/python-sdk/137#-NMmioB68oUuuJLZbt36:-NMmioB68oUuuJLZbt37:b9nga57) (no related file):*
You are missing the `VERSION` bump I think?

___

**Review by blundski — COMMENTED** [review]
> Reviewed 150 of 175 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Exabel/python-sdk/137)* status: Pipfile.lock ignored, all files reviewed, 3 unresolved discussions (waiting on @ivarurdalen)

___
*[`exabel_data_sdk/stubs/exabel/api/data/v1/namespace_service_pb2_grpc.py` line 32 at r1](https://reviewable.io/reviews/Exabel/python-sdk/137#-NMmbbK-EbRYw2LOaeoR:-NMmbbK0-wVg9odKZ2Z4:b7kd0ns) ([raw file](https://github.com/Exabel/python-sdk/blob/ee0d8ba2e69a6c86016a72a285cee18cecb5e88e/exabel_data_sdk/stubs/exabel/api/data/v1/namespace_service_pb2_grpc.py#L32)):*
> ```Python
>         """Lists namespaces.
> 
>         Lists all namespaces accessible to your customer. If you have your own namespace, it will
> ```

Noticed error in this sentence. Should be

it will *be* listed as writeable

This is from a .proto file 
___
*[`exabel_data_sdk/stubs/exabel/api/data/v1/relationship_service_pb2_grpc.py` line 85 at r1](https://reviewable.io/reviews/Exabel/python-sdk/137#-NMmcF3a2QGfTnfulf0u:-NMmcF3a2QGfTnfulf0v:bdsyl6b) ([raw file](https://github.com/Exabel/python-sdk/blob/ee0d8ba2e69a6c86016a72a285cee18cecb5e88e/exabel_data_sdk/stubs/exabel/api/data/v1/relationship_service_pb2_grpc.py#L85)):*
> ```Python
>         """Lists relationship of a specific type.
> 
>         If neither `from_entity` or `to_entity` is given, it is expected that this call will
> ```

Neither ... nor ... ?

Also from a .proto file :S

**Review by blundski — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Exabel/python-sdk/137)* status: Pipfile.lock ignored, all files reviewed, 4 unresolved discussions (waiting on @ivarurdalen)

*[a discussion](https://reviewable.io/reviews/Exabel/python-sdk/137#-NMmoW-R4bc9MNhgb1Sl:-NMmoW-R4bc9MNhgb1Sm:b-wb2o50) (no related file):*
Changelog: fix formatting of --batch-size 

___

**Review by blundski — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Exabel/python-sdk/137#-:-NMmtPfx856dRpRyFc-L:bnfp4nl)* status: Pipfile.lock ignored, all files reviewed, 4 unresolved discussions (waiting on @aksestok and @ivarurdalen)

**Review by aksestok — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/exabel/python-sdk/137)* status: Pipfile.lock ignored, all files reviewed, 3 unresolved discussions (waiting on @ivarurdalen)

**Comment by ivarurdalen** [comment]
<details><summary><i>Previously, blundski wrote…</i></summary><blockquote>

Changelog: fix formatting of --batch-size 
</blockquote></details>

Done.

**Pull request merged**
