### PR TITLE
Update README with information about new APIs

### PR DESCRIPTION
**Pull request by akajoeny**
Updated README with information about Export API, Management API and Analytics API

---
This change is [Reviewable](https://reviewable.io/reviews/exabel/python-sdk/85)

### CODE REVIEW

**Review by aksestok — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/exabel/python-sdk/85)* status: all files reviewed, 6 unresolved discussions (waiting on @akajoeny)

___
*[README.md, line 22 at r1](https://reviewable.io/reviews/exabel/python-sdk/85#-N-7MM5tA015Qz8iAt0X:-N-7MM5tA015Qz8iAt0Y:b-iz9efu) ([raw file](https://github.com/exabel/python-sdk/blob/4e411ab3077687de9c8e4f8a4ffc51a7a201b9d6/README.md#L22)):*
> ```Markdown
> To use the SDK againts Exabel APIs, you need an API key provided by Exabel.
> 
> The Exabel Export API can be used by authenticating with username and password, [Export script](https://doc.exabel.com/api/export/script.html)
> ```

Maybe some more context on the link?
`... with username and password, see the [export script](https://doc.exabel.com/api/export/script.html) for more details.`
___
*[README.md, line 33 at r1](https://reviewable.io/reviews/exabel/python-sdk/85#-N-7MsGl-crn_LNmN5nb:-N-7MsGl-crn_LNmN5nc:b-afe8zi) ([raw file](https://github.com/exabel/python-sdk/blob/4e411ab3077687de9c8e4f8a4ffc51a7a201b9d6/README.md#L33)):*
> ```Markdown
> The Exabel Data API can be used to upload custom data to the Exabel platform. Custom data may include entities, relationships and time series.
> 
> Developer guide: https://help.exabel.com/docs/data-api
> ```

Rewrite as markdown links?
___
*[README.md, line 36 at r1](https://reviewable.io/reviews/exabel/python-sdk/85#-N-7Mmaw3bOGzM19ehFS:-N-7MmaxAiYy9jr5I4pG:b-qr0gzo) ([raw file](https://github.com/exabel/python-sdk/blob/4e411ab3077687de9c8e4f8a4ffc51a7a201b9d6/README.md#L36)):*
> ```Markdown
> 
> ### Export API
> The Exabel Export API can be used to export dashboards and signals from the Exabel Platform
> ```

Missing punctuation mark.
___
*[README.md, line 38 at r1](https://reviewable.io/reviews/exabel/python-sdk/85#-N-7MyP14ssI9SCw6_L7:-N-7MyP22MtCk4vYl6-q:b-afe8zi) ([raw file](https://github.com/exabel/python-sdk/blob/4e411ab3077687de9c8e4f8a4ffc51a7a201b9d6/README.md#L38)):*
> ```Markdown
> The Exabel Export API can be used to export dashboards and signals from the Exabel Platform
> 
> Developer guide: https://doc.exabel.com/api/export/index.html
> ```

Rewrite as markdown links?
___
*[README.md, line 43 at r1](https://reviewable.io/reviews/exabel/python-sdk/85#-N-7MzlQ-n02BxnoLGgR:-N-7MzlR-tjBwv2uJFEz:b-afe8zi) ([raw file](https://github.com/exabel/python-sdk/blob/4e411ab3077687de9c8e4f8a4ffc51a7a201b9d6/README.md#L43)):*
> ```Markdown
> The Exabel Analytics API can be used to manage derived signals and prediction models on the Exabel Platform.
> 
> Develper guide: https://help.exabel.com/docs/analytics-api
> ```

Rewrite as markdown links?
___
*[README.md, line 48 at r1](https://reviewable.io/reviews/exabel/python-sdk/85#-N-7N1-91odqCeCPNy7B:-N-7N1-91odqCeCPNy7C:b-afe8zi) ([raw file](https://github.com/exabel/python-sdk/blob/4e411ab3077687de9c8e4f8a4ffc51a7a201b9d6/README.md#L48)):*
> ```Markdown
> The Exabel Management API can be used to manage the library on the Exabel Platform.
> 
> Developer guide: https://help.exabel.com/docs/management-api
> ```

Rewrite as markdown links?

**Review by akajoeny — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/exabel/python-sdk/85)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @aksestok)

___
*[`README.md` line 22 at r1](https://reviewable.io/reviews/exabel/python-sdk/85#-N-7MM5tA015Qz8iAt0X:-N1Ju8EkCLJ7d6rnvU2U:b-bt5enq) ([raw file](https://github.com/exabel/python-sdk/blob/4e411ab3077687de9c8e4f8a4ffc51a7a201b9d6/README.md#L22)):*
<details><summary><i>Previously, aksestok (Aksel Stokseth) wrote…</i></summary><blockquote>

Maybe some more context on the link?
`... with username and password, see the [export script](https://doc.exabel.com/api/export/script.html) for more details.`
</blockquote></details>

Added context
___
*[`README.md` line 36 at r1](https://reviewable.io/reviews/exabel/python-sdk/85#-N-7Mmaw3bOGzM19ehFS:-N1JuRzVCX8KuGQvCDBs:bi9estx) ([raw file](https://github.com/exabel/python-sdk/blob/4e411ab3077687de9c8e4f8a4ffc51a7a201b9d6/README.md#L36)):*
<details><summary><i>Previously, aksestok (Aksel Stokseth) wrote…</i></summary><blockquote>

Missing punctuation mark.
</blockquote></details>

:pray:

**Review by akajoeny — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/exabel/python-sdk/85)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @aksestok and @zac-yang)

___
*[`README.md` line 38 at r2](https://reviewable.io/reviews/exabel/python-sdk/85#-N-7KuMK8Dtxo8hB55sV-r2-38:-N1N3uHSDkOCrxlscY4Y:b-oldv3) ([raw file](https://github.com/exabel/python-sdk/blob/f5bde29ed044cfd4ed96a7c8723d36084d7ed09c/README.md#L38)):*
<details><summary><i>Previously, zac-yang (Zac Yang) wrote…</i></summary><blockquote>

This doc.exabel.com page already points to https://help.exabel.com/docs/exporting-via-exabel-sdk, maybe we should point directly there from here?
</blockquote></details>

Of course! Changed. Thanks

**Review by aksestok — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/exabel/python-sdk/85#-:-N1ND0yV9SS7-DzW-M8w:bg7igkv)* status: all files reviewed, 1 unresolved discussion (waiting on @zac-yang)

**Review by zac-yang — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/exabel/python-sdk/85#-:-N1NG6hv1W4JmhnzjvD4:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
