### PR TITLE
Documentation + new version

### PR DESCRIPTION
**Pull request by blundski**
added to README + up'ed version

---
This change is [Reviewable](https://reviewable.io/reviews/exabel/python-sdk/19)

### CODE REVIEW

**Review by taral — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/exabel/python-sdk/19)* status: 1 of 2 files reviewed, 5 unresolved discussions (waiting on @blundski)

___
*[README.md, line 5 at r1](https://reviewable.io/reviews/exabel/python-sdk/19#-MTG7EpRB1Q-kRwbfQFu:-MTG7EpRB1Q-kRwbfQFv:b-5qmj35) ([raw file](https://github.com/exabel/python-sdk/blob/855ebbf46ece2111eb22a171d160ea113b14f752/README.md#L5)):*
> ```Markdown
> A Python SDK which provides easy access to the Exabel Data API.
> 
> # Install
> ```

Installation
___
*[README.md, line 13 at r1](https://reviewable.io/reviews/exabel/python-sdk/19#-MTG7ONn5UXRqK0SkGWj:-MTG7ONn5UXRqK0SkGWk:bqki3ku) ([raw file](https://github.com/exabel/python-sdk/blob/855ebbf46ece2111eb22a171d160ea113b14f752/README.md#L13)):*
> ```Markdown
> or download from [PyPI](https://pypi.org/project/exabel-data-sdk/). 
> 
> The SDK requires Python >= 3.6
> ```

“... requires Python 3.6 or later.”
___
*[README.md, line 19 at r1](https://reviewable.io/reviews/exabel/python-sdk/19#-MTG7NNbAcdkz5rA-GpY:-MTG7NNbAcdkz5rA-GpZ:b46b6d2) ([raw file](https://github.com/exabel/python-sdk/blob/855ebbf46ece2111eb22a171d160ea113b14f752/README.md#L19)):*
> ```Markdown
> Contact Exabel to get access to the Data API documentation.
> 
> # Develop
> ```

Development
___
*[README.md, line 21 at r1](https://reviewable.io/reviews/exabel/python-sdk/19#-MTG8TniD8r0Y7AtJX48:-MTG8TniD8r0Y7AtJX49:bwl6fip) ([raw file](https://github.com/exabel/python-sdk/blob/855ebbf46ece2111eb22a171d160ea113b14f752/README.md#L21)):*
> ```Markdown
> # Develop
> 
> To develop against the Data API backend using the SDK you will need an API key and a URL for the API host provided by Exabel.
> ```

The URL itself is available as part of the SDK, so it’s not necessary to mention it here.
___
*[README.md, line 23 at r1](https://reviewable.io/reviews/exabel/python-sdk/19#-MTG7hyc5eliuFvMxOtR:-MTG7hyc5eliuFvMxOtS:b9bbd1o) ([raw file](https://github.com/exabel/python-sdk/blob/855ebbf46ece2111eb22a171d160ea113b14f752/README.md#L23)):*
> ```Markdown
> To develop against the Data API backend using the SDK you will need an API key and a URL for the API host provided by Exabel.
> 
> Scripts for operations against the API can be found [here](https://github.com/Exabel/python-sdk/tree/main/exabel_data_sdk/scripts).
> ```

Don’t use `here` as the name of a link. Rather make a link with a meaningful name, e.g.,

`[Scripts for operations against the API](https://...)`

**Review by blundski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/exabel/python-sdk/19)* status: 1 of 2 files reviewed, 5 unresolved discussions (waiting on @taral)

___
*[README.md, line 5 at r1](https://reviewable.io/reviews/exabel/python-sdk/19#-MTG7EpRB1Q-kRwbfQFu:-MTGCJFWAbwGirlzTdIV:b-896fix) ([raw file](https://github.com/exabel/python-sdk/blob/855ebbf46ece2111eb22a171d160ea113b14f752/README.md#L5)):*
<details><summary><i>Previously, taral wrote…</i></summary><blockquote>

Installation
</blockquote></details>

Done.
___
*[README.md, line 13 at r1](https://reviewable.io/reviews/exabel/python-sdk/19#-MTG7ONn5UXRqK0SkGWj:-MTGCJdX1tYn65-GlPIT:b-896fix) ([raw file](https://github.com/exabel/python-sdk/blob/855ebbf46ece2111eb22a171d160ea113b14f752/README.md#L13)):*
<details><summary><i>Previously, taral wrote…</i></summary><blockquote>

“... requires Python 3.6 or later.”
</blockquote></details>

Done.
___
*[README.md, line 19 at r1](https://reviewable.io/reviews/exabel/python-sdk/19#-MTG7NNbAcdkz5rA-GpY:-MTGCksgDgpxfOykDXZr:b-896fix) ([raw file](https://github.com/exabel/python-sdk/blob/855ebbf46ece2111eb22a171d160ea113b14f752/README.md#L19)):*
<details><summary><i>Previously, taral wrote…</i></summary><blockquote>

Development
</blockquote></details>

Done.
___
*[README.md, line 21 at r1](https://reviewable.io/reviews/exabel/python-sdk/19#-MTG8TniD8r0Y7AtJX48:-MTGCOMJ9oWT0BT0qpZa:b-896fix) ([raw file](https://github.com/exabel/python-sdk/blob/855ebbf46ece2111eb22a171d160ea113b14f752/README.md#L21)):*
<details><summary><i>Previously, taral wrote…</i></summary><blockquote>

The URL itself is available as part of the SDK, so it’s not necessary to mention it here.
</blockquote></details>

Done.
___
*[README.md, line 23 at r1](https://reviewable.io/reviews/exabel/python-sdk/19#-MTG7hyc5eliuFvMxOtR:-MTGCQOC4ba42n_WoAUk:b-896fix) ([raw file](https://github.com/exabel/python-sdk/blob/855ebbf46ece2111eb22a171d160ea113b14f752/README.md#L23)):*
<details><summary><i>Previously, taral wrote…</i></summary><blockquote>

Don’t use `here` as the name of a link. Rather make a link with a meaningful name, e.g.,

`[Scripts for operations against the API](https://...)`
</blockquote></details>

Done.

**Review by taral — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/exabel/python-sdk/19)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @blundski and @taral)

___
*[README.md, line 19 at r1](https://reviewable.io/reviews/exabel/python-sdk/19#-MTG7NNbAcdkz5rA-GpY:-MTGDhZu95FjzvSR4ILK:buoedrd) ([raw file](https://github.com/exabel/python-sdk/blob/855ebbf46ece2111eb22a171d160ea113b14f752/README.md#L19)):*
<details><summary><i>Previously, blundski wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don’t see this change. Did you push it?

**Review by taral — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/exabel/python-sdk/19#-:-MTGEriK6KGXsRhc2VMX:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
