### PR TITLE
Change upsert methods to use server side upsert

### PR DESCRIPTION
**Pull request by aksestok**
This change is [Reviewable](https://reviewable.io/reviews/exabel/python-sdk/63)

### CODE REVIEW

**Review by hallarak — CHANGES_REQUESTED** [review]
> Reviewed 23 of 23 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/exabel/python-sdk/63)* status: all files reviewed, 1 unresolved discussion (waiting on @aksestok)

___
*[VERSION, line 1 at r1](https://reviewable.io/reviews/exabel/python-sdk/63#-MvXxGzFEDOf0QL-VnAh:-MvXxGzG0L9U5civRKyy:b7qrshq) ([raw file](https://github.com/exabel/python-sdk/blob/c2597ce578839743d3f59d807281f88d1ca94e2b/VERSION#L1)):*
> ```
> 2.6.0
> ```

There are some backwards-incompatible changes, like removing arguments and changing return types. We should probably bump the major version?

**Review by aksestok — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/exabel/python-sdk/63)* status: all files reviewed, 1 unresolved discussion (waiting on @hallarak)

___
*[VERSION, line 1 at r1](https://reviewable.io/reviews/exabel/python-sdk/63#-MvXxGzFEDOf0QL-VnAh:-MvXznhWBgPoyo-l3rW5:b4v1he3) ([raw file](https://github.com/exabel/python-sdk/blob/c2597ce578839743d3f59d807281f88d1ca94e2b/VERSION#L1)):*
<details><summary><i>Previously, hallarak (Øystein Hallaråker) wrote…</i></summary><blockquote>

There are some backwards-incompatible changes, like removing arguments and changing return types. We should probably bump the major version?
</blockquote></details>

I agree, bumping major instead.

**Review by hallarak — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/exabel/python-sdk/63#-:-MvY-KxH50tRhJV1bXMG:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by zac-yang** [comment]
Any impact on CSV uploader that I should reflect in user guide?

**Comment by aksestok** [comment]
No. There is no difference in end-user facing behaviour.

Best regards,

*Aksel Stokseth*
Data Engineer | Exabel AS
***@***.*** | +47 40 48 04 58

**Pull request merged**
