### PR TITLE
First version of the data sdk

### PR DESCRIPTION
**Pull request by taral**
This change is [Reviewable](https://reviewable.io/reviews/exabel/python-sdk/1)

### CODE REVIEW

**Review by taral — COMMENTED** [review]
Requested review from @bnordli for the build (Jenkinsfile), @hallarak for the Python code and @oyvindwe for license and other settings (primarily setup.py), but of course feel free to have opinions on other things.

> *[Reviewable](https://reviewable.io/reviews/exabel/python-sdk/1#-:-MQqf7wm5r0pLInDa0ZU:b-g5a4z2)* status: 0 of 112 files reviewed, all discussions resolved

**Review by oyvindwe — CHANGES_REQUESTED** [review]
> Reviewed 2 of 112 files at r1, 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/exabel/python-sdk/1)* status: 3 of 112 files reviewed, 1 unresolved discussion (waiting on @taral)

___
*[setup.py, line 11 at r2](https://reviewable.io/reviews/exabel/python-sdk/1#-MQqtvpO757TcsLc2qDD:-MQqtvpO757TcsLc2qDE:b-g2yhh0) ([raw file](https://github.com/exabel/python-sdk/blob/076f3976953e6bc14abfc8329cea9699882a64ac/setup.py#L11)):*
> ```Python
>     author="Exabel",
>     author_email="support@exabel.com",
>     description="Exabel’s Python SDK for the data API",
> ```

`Python SDK for the Exabel Data API`

**Review by taral — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/exabel/python-sdk/1)* status: 2 of 112 files reviewed, 1 unresolved discussion (waiting on @oyvindwe)

___
*[setup.py, line 11 at r2](https://reviewable.io/reviews/exabel/python-sdk/1#-MQqtvpO757TcsLc2qDD:-MQqv0GE5OLg_rtWfCCj:b-896fix) ([raw file](https://github.com/exabel/python-sdk/blob/076f3976953e6bc14abfc8329cea9699882a64ac/setup.py#L11)):*
<details><summary><i>Previously, oyvindwe (Øyvind Matheson Wergeland) wrote…</i></summary><blockquote>

`Python SDK for the Exabel Data API`
</blockquote></details>

Done.

**Review by oyvindwe — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/exabel/python-sdk/1)* status: 3 of 112 files reviewed, all discussions resolved

**Review by hallarak — CHANGES_REQUESTED** [review]
Should we include a pipfile in the repo?

> Reviewed 105 of 112 files at r1, 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/exabel/python-sdk/1#-:-MQr4S5hB280SqxYwv2h:b5la59t)* status: 110 of 112 files reviewed, 1 unresolved discussion (waiting on @taral)

___
*[exabel_data_sdk/stubs/exabel/api/data/v1/all_pb2_grpc.py, line 1 at r3](https://reviewable.io/reviews/exabel/python-sdk/1#-MQr2KKh2_SnO-7FrBoD:-MQr2KKi64lUaIpCoKLB:b-phamca) ([raw file](https://github.com/exabel/python-sdk/blob/cf1acc2d50226de61a1d5ecf7824a68e50962704/exabel_data_sdk/stubs/exabel/api/data/v1/all_pb2_grpc.py#L1)):*
> ```Python
> # Generated by generate_protobuf_stubs.sh.
> ```

I guess we could potentially also include this generate script in this repo? And maybe some instructions on how to update the stubs?

**Review by oyvindwe — COMMENTED** [review]
Pipfiles are intended for executables, not libraries, as I understand it.

> *[Reviewable](https://reviewable.io/reviews/exabel/python-sdk/1#-:-MQr5nq-Ak1S-toXI4xL:bo2hqvy)* status: 110 of 112 files reviewed, 1 unresolved discussion (waiting on @taral)

**Review by bnordli — CHANGES_REQUESTED** [review]
(Not reviewing the python code.)

> Reviewed 9 of 112 files at r1, 2 of 3 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/exabel/python-sdk/1#-:-MQr86s2AQsLe6WL47oy:b559jtj)* status: all files reviewed, 4 unresolved discussions (waiting on @taral)

___
*[build.sh, line 5 at r3](https://reviewable.io/reviews/exabel/python-sdk/1#-MQr7MV21tWZ3-k53kR5:-MQr7MV31_AFMJYTuSAX:bb0mpa9) ([raw file](https://github.com/exabel/python-sdk/blob/cf1acc2d50226de61a1d5ecf7824a68e50962704/build.sh#L5)):*
> ```Shell
> # Runs first all the style checks and tests, and if they succeed, builds the files for distribution.
> 
> set -e
> ```

`set -euf` is the current best practice.
___
*[publish.sh, line 10 at r3](https://reviewable.io/reviews/exabel/python-sdk/1#-MQr7fMh5ujz48dyd3g_:-MQr7fMiE_p79-8iUBiU:b-edsm67) ([raw file](https://github.com/exabel/python-sdk/blob/cf1acc2d50226de61a1d5ecf7824a68e50962704/publish.sh#L10)):*
> ```Shell
> # while the password is the token generated by PyPI for the account.
> 
> set -e
> ```

`set -euf`?
___
*[publish.sh, line 15 at r3](https://reviewable.io/reviews/exabel/python-sdk/1#-MQr7hcO9SMsk4K0FvBR:-MQr7hcO9SMsk4K0FvBS:bpmgr4o) ([raw file](https://github.com/exabel/python-sdk/blob/cf1acc2d50226de61a1d5ecf7824a68e50962704/publish.sh#L15)):*
> ```Shell
> 
> while getopts 'r' c; do
>   case $c in
> ```

`"${c}"` unless there is a good reason not to.

**Review by taral — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/exabel/python-sdk/1)* status: all files reviewed, 4 unresolved discussions (waiting on @bnordli and @hallarak)

___
*[build.sh, line 5 at r3](https://reviewable.io/reviews/exabel/python-sdk/1#-MQr7MV21tWZ3-k53kR5:-MQrEuIH92TSKamTuIQ1:b-896fix) ([raw file](https://github.com/exabel/python-sdk/blob/cf1acc2d50226de61a1d5ecf7824a68e50962704/build.sh#L5)):*
<details><summary><i>Previously, bnordli (Børge Nordli) wrote…</i></summary><blockquote>

`set -euf` is the current best practice.
</blockquote></details>

Done.
___
*[publish.sh, line 10 at r3](https://reviewable.io/reviews/exabel/python-sdk/1#-MQr7fMh5ujz48dyd3g_:-MQrEuurBImh2mX1E3D3:b-896fix) ([raw file](https://github.com/exabel/python-sdk/blob/cf1acc2d50226de61a1d5ecf7824a68e50962704/publish.sh#L10)):*
<details><summary><i>Previously, bnordli (Børge Nordli) wrote…</i></summary><blockquote>

`set -euf`?
</blockquote></details>

Done.
___
*[publish.sh, line 15 at r3](https://reviewable.io/reviews/exabel/python-sdk/1#-MQr7hcO9SMsk4K0FvBR:-MQrF0xN9CAuf1qB1TV6:b-896fix) ([raw file](https://github.com/exabel/python-sdk/blob/cf1acc2d50226de61a1d5ecf7824a68e50962704/publish.sh#L15)):*
<details><summary><i>Previously, bnordli (Børge Nordli) wrote…</i></summary><blockquote>

`"${c}"` unless there is a good reason not to.
</blockquote></details>

Done.
___
*[exabel_data_sdk/stubs/exabel/api/data/v1/all_pb2_grpc.py, line 1 at r3](https://reviewable.io/reviews/exabel/python-sdk/1#-MQr2KKh2_SnO-7FrBoD:-MQrFI16035beerfQcUF:bujrkrx) ([raw file](https://github.com/exabel/python-sdk/blob/cf1acc2d50226de61a1d5ecf7824a68e50962704/exabel_data_sdk/stubs/exabel/api/data/v1/all_pb2_grpc.py#L1)):*
<details><summary><i>Previously, hallarak (Øystein Hallaråker) wrote…</i></summary><blockquote>

I guess we could potentially also include this generate script in this repo? And maybe some instructions on how to update the stubs?
</blockquote></details>

Yes, but the protobuf files are not currently in a public repo, so I don’t think that script is particularly useful without those. When we publish the protobuf files, we may include the script.

**Review by taral — COMMENTED** [review]
A Pipfile was not required to build and publish the package.

> *[Reviewable](https://reviewable.io/reviews/exabel/python-sdk/1#-:-MQrG6VD780odD5HsDyQ:b-ewtq04)* status: 109 of 112 files reviewed, 4 unresolved discussions (waiting on @bnordli and @hallarak)

**Review by bnordli — APPROVED** [review]
> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/exabel/python-sdk/1)* status: all files reviewed, 1 unresolved discussion (waiting on @hallarak)

**Review by hallarak — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/exabel/python-sdk/1)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[exabel_data_sdk/stubs/exabel/api/data/v1/all_pb2_grpc.py, line 1 at r3](https://reviewable.io/reviews/exabel/python-sdk/1#-MQr2KKh2_SnO-7FrBoD:-MQrPaPPDL13G-pZcS7W:b2nhlkw) ([raw file](https://github.com/exabel/python-sdk/blob/cf1acc2d50226de61a1d5ecf7824a68e50962704/exabel_data_sdk/stubs/exabel/api/data/v1/all_pb2_grpc.py#L1)):*
<details><summary><i>Previously, taral wrote…</i></summary><blockquote>

Yes, but the protobuf files are not currently in a public repo, so I don’t think that script is particularly useful without those. When we publish the protobuf files, we may include the script.
</blockquote></details>

Ok!

**Pull request merged**
