### PR TITLE
Expose create_library_signal and create_tag

### PR DESCRIPTION
**Pull request by oyvindwe**
This change is [Reviewable](https://reviewable.io/reviews/exabel/python-sdk/33)

### CODE REVIEW

**Review by hallarak — COMMENTED** [review]
> Reviewed 8 of 12 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/exabel/python-sdk/33)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[exabel_data_sdk/client/api/time_series_api.py, line 130 at r2](https://reviewable.io/reviews/exabel/python-sdk/33#-Me58S82AVwf8ptXlWIF:-Me58S82AVwf8ptXlWIG:byfiia) ([raw file](https://github.com/exabel/python-sdk/blob/6b575e3ebaa6b4cf0c483707ef62a73a553b77d1/exabel_data_sdk/client/api/time_series_api.py#L130)):*
> ```Python
>                     and if ns1 is not empty, all three namespaces must be equal.
>             series: The time series data
>             create_tag: Set to true to create a tag for every entity type a signal has time series
> ```

I think we try to keep the description of parameters on the same indentation.

**Review by oyvindwe — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/exabel/python-sdk/33)* status: 11 of 13 files reviewed, all discussions resolved

___
*[exabel_data_sdk/client/api/time_series_api.py, line 130 at r2](https://reviewable.io/reviews/exabel/python-sdk/33#-Me58S82AVwf8ptXlWIF:-Me5JYRo2PYxeiwq-IPU:b-896fix) ([raw file](https://github.com/exabel/python-sdk/blob/6b575e3ebaa6b4cf0c483707ef62a73a553b77d1/exabel_data_sdk/client/api/time_series_api.py#L130)):*
<details><summary><i>Previously, hallarak (Øystein Hallaråker) wrote…</i></summary><blockquote>

I think we try to keep the description of parameters on the same indentation.
</blockquote></details>

Done.

**Review by hallarak — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/exabel/python-sdk/33)* status: 12 of 13 files reviewed, all discussions resolved

**Review by hallarak — COMMENTED** [review]
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/exabel/python-sdk/33)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by hallarak — COMMENTED** [review]
> Reviewed 5 of 5 files at r5.
> *[Reviewable](https://reviewable.io/reviews/exabel/python-sdk/33)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by hallarak — APPROVED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/exabel/python-sdk/33)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
