### PR TITLE
update relationship-type script

### PR DESCRIPTION
**Pull request by HaakonHam**
This change is [Reviewable](https://reviewable.io/reviews/exabel/python-sdk/68)

### CODE REVIEW

**Review by aksestok — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/exabel/python-sdk/68#-:-Mwexx8W8w-uefuW74LZ:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by zac-yang** [comment]
why do we need 2 arguments for the same thing?

**Review by HaakonHam — COMMENTED** [review]
If you don't use any of them, it will not change. So you need both in order to both be able to add or remove.

> *[Reviewable](https://reviewable.io/reviews/exabel/python-sdk/68#-:-Mweyj6BEHHaGok_2YN7:b-pbkoei)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by zac-yang** [comment]
Wouldn't this be much simpler:
`--is-ownership=True` => set ownership to True
`--is-ownership=False` => set ownership to False

**Comment by aksestok** [comment]
Negating boolean flags with `no-` prefix is standard for all CLIs.

**Comment by zac-yang** [comment]
(I have to document this, so being opinionated here - the common command-line pattern I have seen is what I described ^)

Also - "... is a data set ownership", is a bit unclear. Don't we just mean "ownership relationship"

**Comment by aksestok** [comment]
This is from the API-documentation: https://doc.exabel.com/api/data/relationships.html#create-relationship-type

**Comment by HaakonHam** [comment]
Zac, that was my initial thought as well when doing things like this with the SDK, but it seems to be the standard to do it this way.
https://stackoverflow.com/questions/15008758/parsing-boolean-values-with-argparse

But I agree on that the description in the SDK and the API docs could change to make more sense. 
Let me know what you think makes most sense, and I can update the docs and the SDK.

**Comment by zac-yang** [comment]
Yea I came across that SO thread as well. I suppose I'm more used to seeing single boolean CLI arguments, that when present, modify the default (eg False if no arg, True if has arg) - but that maybe doesn't work in this case because we want the update of the ownership property to be a very explicit choice, as it is very slow?

**Pull request merged**
