### PR TITLE
Release version 3.8.0

### PR DESCRIPTION
**Pull request by aksestok**
# Added
* Specifying entity from and to column are now optional when uploading relationships. The default is to load relationships from the entities in the first column to the entities in the second column.
* Method to get accessible namespaces.
* XASE as potential market in the create entity mapping script.
* Excel (.xslx) as an output format to `FileWriter`.
* Option to force reauthentication of the user when using the Export API.

# Changed
* Slightly improved logging when running SQL queries and uploading resources.
* Removed argument `--description` from delete relationship script (not in use).

# Fixed
* Providing empty identifiers when uploading resources now raises a user friendly error.
* Raise a proper exception when attempting to upload a time series with invalid data points instead of failing silently.

- - -
This change is [Reviewable](https://reviewable.io/reviews/exabel/python-sdk/126)

### CODE REVIEW

**Comment by aksestok** [comment]
CC: @zac-yang and @akajoeny

**Review by burk — APPROVED** [review]
Do you mean `The default is to load relationships from the first to the second column.` in the first point?

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/exabel/python-sdk/126#-:-NA9IIEvAVzLELaIUVP3:bax4rw2)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by aksestok — COMMENTED** [review]
Yes, thank you, made it even clearer as well: `The default is to load relationships from the entities in the first column to the entities in the second column.`

> *[Reviewable](https://reviewable.io/reviews/exabel/python-sdk/126#-:-NA9JeFxDkuMuyTWaHNT:beaqzpk)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by burk — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/exabel/python-sdk/126#-:-NA9K7HR3dsCad2wbW_N:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
